# Spring properties
spring:
  application:
     name: redis-pro
# 配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  redis:
    database: 0
    host: 192.168.1.222
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0

druid:
  name: redis-db
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
# 初始化大小，最小，最大
  initialSize: 10
  minIdle: 10
  maxActive: 200
# 配置获取连接等待超时的时间
  maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,log4j,config
# 合并多个DruidDataSource的监控数据
#   useGlobalDataSourceStat: true
  url: jdbc:mysql://192.168.1.222:3306/redis?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: hive
  #java -cp druid-1.0.16.jar com.alibaba.druid.filter.config.ConfigTools 你的密码(admin123) admin soonfor
  password: jinggo111
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# HTTP Server
server:
  port: 7777   # 动态分配端口

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hbm2ddl.auto: update
  show_sql: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

