# Spring properties
spring:
  application:
     name: redis-pro
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
# 配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    # 自动生成表结构
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#    show-sql: true
# 不利用spring-data-redis整合	整合灵活度更大
  redis:
    database: 0
    host: 120.79.230.147
    port: 6379
    password: redis6751
    # 连接超时时间（毫秒）
    timeout: 60000
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
# Spring Boot 默认的ES 加载
  data:
    elasticsearch:
      cluster-nodes: 120.79.230.147:9300
      cluster-name: elasticsearch

# 自己定义配置启动ES
elasticsearch:
  ip: 192.168.5.111
  port: 9300
  pool: 5
  cluster:
    name: es-logs

druid:
  name: redis-db
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
# 初始化大小，最小，最大
  initialSize: 10
  minIdle: 10
  maxActive: 200
# 配置获取连接等待超时的时间
  maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,log4j,config
# 合并多个DruidDataSource的监控数据
#   useGlobalDataSourceStat: true
  url: jdbc:mysql://120.79.230.147:3306/xboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  #java -cp druid-1.0.16.jar com.alibaba.druid.filter.config.ConfigTools 你的密码(admin123) admin soonfor
  password: bb62661206
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: wang.jinggo.domain
  typeEnumsPackage: wang.jinggo.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# HTTP Server
server:
  port: 7777   # 动态分配端口

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hbm2ddl.auto: update
  show_sql: true

xboot:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # mob api配置 mob官网注册申请即可
  mob:
    appKey: 285b065b754fd
  # ES
  elasticsearch:
    nodeClient: 120.79.230.147:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true
  # 七牛云配置
  qiniu:
    accessKey: pd8EMFJt9IERhDOUAobL_9bB0qJSYBLhyBiFQRTN
    secretKey: m2nwvfRbOi5qxKd-qmbv0wEql8rMsMV4pM_uBLZ9
    bucket: jinggo-blog
    domain: pd2kdimru.bkt.clouddn.com/

# 忽略鉴权url
ignored:
  urls:
    - /xboot/permission/getMenuList/**
    - /xboot/user/regist
    - /xboot/common/**
    - /xboot/es/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**

# Swagger界面内容配置
swagger:
  title: Jinggo API接口文档
  description: Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://jinggo.wang
  contact:
    name: jinggo
    url: http://jinggo.wang
    email: jinggo@sohu.com

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

